name: Lint control

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
      - run: npm ci
      - name: Lint
      - run: npm run lint
